name: Build Check
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install JDK
        run: sudo apt update && sudo apt install -y default-jdk make

      - name: Install Maven
        run: sudo apt install -y maven

      - name: Build a project
        run: make
